export const produtos = [
    { id: 1, nome: "Par de Brincos Articulados Oceano", preco: 40.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-articulados-01.jpg" },
    { id: 2, nome: "Par de Brincos Articulados Coração com Losango", preco: 35.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-articulados-02.jpg" },
    { id: 3, nome: "Par de Brincos Articulados Concha", preco: 40.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-articulados-03.jpg" },
    { id: 4, nome: "Par de Brincos Articulados Esquilo", preco: 40.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-articulados-04.jpg" },
    { id: 5, nome: "Par de Brincos Articulados Gato", preco: 30.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-articulados-05.jpg" },
    { id: 6, nome: "Par de Brincos Floral", preco: 40.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-biojoia-01.jpg" },
    { id: 7, nome: "Par de Brincos Gota", preco: 20.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-gota-01.jpg" },
    { id: 8, nome: "Par de Brincos Pet", preco: 20.00, prazo: "3 dias úteis", tipo: ["novidade", "brinco"], img: "img/brincos-pet-01.jpg" },
    { id: 9, nome: "Chaveiro Mandala Personalizado Amarelo", preco: 25.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-mandala-01.jpg" },
    { id: 10, nome: "Chaveiro Mandala Personalizado Lilás", preco: 25.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-mandala-02.jpg" },
    { id: 11, nome: "Chaveiro Mandala Personalizado Vermelho", preco: 25.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-mandala-03.jpg" },
    { id: 12, nome: "Chaveiro Mandala Personalizado Azul", preco: 25.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-mandala-04.jpg" },
    { id: 13, nome: "Chaveiro Personalizado Otaku", preco: 35.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-otaku-01.jpg" },
    { id: 14, nome: "Chaveiro Religioso", preco: 20.00, prazo: "3 dias úteis", tipo: ["novidade", "chaveiro"], img: "img/chaveiro-religioso-01.jpg" },
    { id: 15, nome: "Letra Avulsa Personalizada Roxo com Ouro", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-01.jpg" },
    { id: 16, nome: "Letra Avulsa Personalizada Preto com Ouro", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-02.jpg" },
    { id: 17, nome: "Letra Avulsa Personalizada Lilás com Ouro", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-03.jpg" },
    { id: 18, nome: "Letra Avulsa Personalizada Marrom com Ouro", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-04.jpg" },
    { id: 19, nome: "Letra Avulsa Personalizada Rosa", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-05.jpg" },
    { id: 20, nome: "Letra Avulsa Personalizada Marrom com Corações Amarelos", preco: 16.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-06.jpg" },
    { id: 21, nome: "Letra Avulsa Personalizada Vermelho com Cores Sortidas ", preco: 15.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-07.jpg" },
    { id: 22, nome: "Letra Avulsa Personalizada Azul com Detalhes", preco: 17.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-08.jpg" },
    { id: 23, nome: "Letra Avulsa Personalizada Dourado com Ouro e Glitter", preco: 17.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-09.jpg" },
    { id: 24, nome: "Letra Avulsa Personalizada Laranja com Detalhes em Vermelho", preco: 16.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-10.jpg" },
    { id: 25, nome: "Letra Avulsa Personalizada Preto com Brilhos", preco: 16.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-11.jpg" },
    { id: 26, nome: "Letra Avulsa Personalizada Rosa com Ouro", preco: 16.00, prazo: "3 dias úteis", tipo: ["novidade", "letra"], img: "img/letra-avulsa-12.jpg" },
    { id: 27, nome: "Pingente Pet - Patinha", preco: 10.00, prazo: "3 dias úteis", tipo: ["novidade", "pingente"], img: "img/pingente-pet-01.jpg" },
    { id: 28, nome: "Porta Copos Personalizado 01", preco: 50.00, prazo: "4 dias úteis", tipo: ["novidade", "porta-copo"], img: "img/porta-copo-personalizado-01.jpg" },
    { id: 29, nome: "Porta Copos Personalizado 02", preco: 50.00, prazo: "4 dias úteis", tipo: ["novidade", "porta-copo"], img: "img/porta-copo-personalizado-02.jpg" },
    { id: 30, nome: "Porta Copos Personalizado gatos Yin-Yang", preco: 50.00, prazo: "4 dias úteis", tipo: ["novidade", "porta-copo"], img: "img/porta-copos-personalizados-03.jpg" },
    { id: 31, nome: "Porta Copos Personalizado Azul com Ouro", preco: 40.00, prazo: "3 dias úteis", tipo: ["novidade", "porta-copo"], img: "img/porta-copos-personalizados-04.jpg" }
];